FROM prestashop/prestashop:1.7.8.10-apache

# Instalacja narzędzi i Memcached
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        default-mysql-client \
        make g++ autoconf pkg-config \
        libmemcached-dev \
        zlib1g-dev \
        libssl-dev && \
    a2enmod ssl && \
    pecl install memcached && \
    docker-php-ext-enable memcached && \
    rm -rf /var/lib/apt/lists/*

# Copy modified start script
COPY docker_run.sh /tmp/docker_run.sh
RUN chmod +x /tmp/docker_run.sh

# Create init scripts directory and copy scripts for enabling modules
RUN mkdir -p /tmp/init-scripts/
COPY enable_modules.php /tmp/init-scripts/enable_modules.php
COPY enable_modules.sh /tmp/init-scripts/enable_modules.sh
RUN chmod +x /tmp/init-scripts/enable_modules.php /tmp/init-scripts/enable_modules.sh

# Build: Copy source code
COPY src /var/www/html
COPY static/img /var/www/html/img
COPY Docker/mysql/init/dump.sql /tmp/db_dump/dump.sql

# Permissions & Cleanup
RUN chown -R www-data:www-data /var/www/html && \
    rm -rf /var/www/html/var/cache/* /var/www/html/var/logs/*

# Copy SSL certificates
COPY nginx/ssl/nginx-selfsigned.crt /etc/ssl/certs/ssl-cert-snakeoil.pem
COPY nginx/ssl/nginx-selfsigned.key /etc/ssl/private/ssl-cert-snakeoil.key

# Create SSL site config
RUN echo '<VirtualHost *:443>\n\
    ServerAdmin webmaster@localhost\n\
    DocumentRoot /var/www/html\n\
    ErrorLog ${APACHE_LOG_DIR}/error.log\n\
    CustomLog ${APACHE_LOG_DIR}/access.log combined\n\
    SSLEngine on\n\
    SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem\n\
    SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key\n\
    <FilesMatch "\.(cgi|shtml|phtml|php)$">\n\
        SSLOptions +StdEnvVars\n\
    </FilesMatch>\n\
    <Directory /usr/lib/cgi-bin>\n\
        SSLOptions +StdEnvVars\n\
    </Directory>\n\
    <Directory /var/www/html>\n\
        Options Indexes FollowSymLinks\n\
        AllowOverride All\n\
        Require all granted\n\
    </Directory>\n\
</VirtualHost>' > /etc/apache2/sites-available/default-ssl.conf && a2ensite default-ssl

# Set correct permissions for SSL certificates
RUN chown root:www-data /etc/ssl/private/ssl-cert-snakeoil.key && \
    chmod 640 /etc/ssl/private/ssl-cert-snakeoil.key

# Set Apache environment variables
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_PID_FILE /var/run/apache2/apache2.pid
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

# Ensure Apache run directory exists
RUN mkdir -p /var/run/apache2

CMD ["/tmp/docker_run.sh"]
