FROM prestashop/prestashop:1.7.8.10-fpm

# Instalacja narzędzi i Memcached
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        default-mysql-client \
        make g++ autoconf pkg-config \
        libmemcached-dev \
        zlib1g-dev \
        libssl-dev && \
    pecl install memcached && \
    docker-php-ext-enable memcached && \
    apt-get purge -y --auto-remove make g++ autoconf pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*

# Copy modified start script
COPY docker_run.sh /tmp/docker_run.sh
RUN chmod +x /tmp/docker_run.sh

# Build: Copy source code
COPY src /var/www/html
COPY static/img /var/www/html/img
COPY Docker/mysql/init/dump.sql /tmp/db_dump/dump.sql

# Permissions & Cleanup
RUN chown -R www-data:www-data /var/www/html && \
    rm -rf /var/www/html/var/cache/* /var/www/html/var/logs/*

CMD ["/tmp/docker_run.sh"]
