services:
  prestashop:
    image: krzkacz887/prestashop-app:v1.2
    restart: unless-stopped
    environment:
      DB_SERVER: student-swarm01
      DB_PORT: 3306
      DB_NAME: BE_197778
      DB_USER: root
      DB_PASSWD: student
      DB_PREFIX: ps_
      PS_INSTALL_AUTO: 1
      PS_ERASE_DB: 1
      PS_INSTALL_DB: 1
      PS_PORT: 19795
      PS_DOMAIN: localhost:19795
      PS_LANGUAGE: pl
      PS_COUNTRY: pl
      PS_ALL_LANGUAGES: 0
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
      ADMIN_MAIL: admin@gmial.com
      ADMIN_PASSWD: AdminPassword123
      PS_ENABLE_SSL: 1
      PS_HANDLE_DYNAMIC_DOMAIN: 0
      PS_DEMO_MODE: 0
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
    networks:
      - network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == student-swarm01
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G

  nginx:
    image: krzkacz887/prestashop-nginx:v1.2
    restart: unless-stopped
    depends_on:
      - prestashop
    ports:
     - target: 443
       published: 19795
       mode: host
    networks:
      - network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == student-swarm01
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 0.5G

  memcached:
    image: memcached:alpine
    restart: unless-stopped
    networks:
      - network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == student-swarm01
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  network:
